### PR TITLE
Sync to master up to 25 Sep

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

**Protocol version**
8.60

### Changes Proposed

**Issues addressed:** 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by Znote** [comment]
Not sure if it should sync to master anymore, but instead sync to TFS 1.4 branch:
https://github.com/otland/forgottenserver/commits/1.4

**Comment by EPuncker** [comment]
> 

there are features in master that will still be useful to any tibia version, while 1.4.1 will receive only "fix" content

**Review by luanluciano93 — APPROVED** [review]

**Comment by luanluciano93** [comment]
what is required for this pull request to be approved?

**Comment by Znote** [comment]
> > 
> 
> there are features in master that will still be useful to any tibia version, while 1.4.1 will receive only "fix" content

I still think we should at least sync to 1.4.1 first at least, and then perhaps open a new PR for the remaining stuff. 

We might also consider maintaining an 10.98 branch, then we can filter out protocol 12 stuff into a protocol 10 branch, and then filter out protocol 10 stuff to this 8.6 branch.

**Pull request closed without merging**
