### PR TITLE
Updated map with the one from upstream

### PR DESCRIPTION
**Pull request by EPuncker**
Fixed most of the doors

### CODE REVIEW

**Comment by EPuncker** [comment]
> ```
> >> Loading map
> > Map size: 2048x2048.
> [Fatal - Map::loadMap] [x:233, y:451, z:13] Failed to create item.
> > ERROR: Failed to load map
> >> No services running. The server is NOT online.
> ```

fixed, it was some lava I forgot to remove

**Comment by Znote** [comment]
Ohh wow, yeah. My map editor also says its 6255...
image

But in-game:
image

Hmmm

Edit: Must be something is wrong with my setup, I'm always screwing up data pack testing. >.<

**Comment by Znote** [comment]
Ok, total headache trying to figure out wtf is going on with my setup, so I copied the door in the house and added them outside the house, along with 1 that is the locked door:
image


Guess what happens when I spin up the server?
image

😩😩😩😩

Its like the door is getting replaced on bootup, perhaps it is recognized as a house, and the door type gets switched around?

**Comment by EPuncker** [comment]
> (I am pretty sure this is an Upstream-bug, will verify soon).

[it is](https://otland.net/threads/bug-house-door-tfs-1-0.239124/) indeed, even I had this "bug" back in the days

**Comment by nekiro** [comment]
Doors are probably handled like regular house items, thus they are saved inside of tile_store, upstream is probably missing isDoor check somewhere in saving house items.

**Comment by EPuncker** [comment]
> Doors are probably handled like regular house items, thus they are saved inside of tile_store, upstream is probably missing isDoor check somewhere in saving house items.
> 
> Reference: https://github.com/otland/forgottenserver/blob/master/src/iomapserialize.cpp#L250
> From my understanding we are saving doors, because doors have custom description (owner info)

I suppose they are being saved only because of the closed/open state since that is persistent

**Comment by Znote** [comment]
> Doors are probably handled like regular house items, thus they are saved inside of tile_store, upstream is probably missing isDoor check somewhere in saving house items.
> 
> Reference: https://github.com/otland/forgottenserver/blob/master/src/iomapserialize.cpp#L250
> From my understanding we are saving doors, because doors have custom description (owner info) and this thing is set when owner is changed. I think the fix would be to find doors on houses load and set the description instead of saving it into database.

Probably because we want to save the state of the doors and windows. You want to close or open a window or door, the itemid is different. Would be annoying to login every day after server save to close your windows so people dont throw garbage inside. :P This is probably why this is saved. 

Solution I think is to compare itemid with otbm source, if its different, save it, else don't save it. 

Then if you open a door, shut down server, it will still be the old opened door. But if you close it again, the next time server boots it will be fixed to what is configured in RME. Which makes life alot easier.

**Comment by EPuncker** [comment]
> so people dont throw garbage inside.

btw that is not possible anymore xD only house owners and invited people can move/throw things now

**Review by Znote — APPROVED** [review]
image
image

Finally cleaned up my mess, PR works great, and resolves both: https://github.com/nekiro/TFS-1.4-Downgrades/issues/14 and https://github.com/nekiro/TFS-1.4-Downgrades/issues/15

@nekiro you are the merge master. :P

**Comment by nekiro** [comment]
I find this pull request pretty redundant as no one gonna use this map anyway, but yeah I can merge it.

**Comment by Znote** [comment]
I'm using it all the time for testing. :P

**Pull request merged**
