### PR TITLE
Fix monster definitions

### PR DESCRIPTION
**Pull request by dnvd**
Fixed stalker name typo in summon definition.
Some boss monsters also had summon chance set to value*100 which printed errors in console because value was >1000.
Also fixed mahrdis.xml attack missing a closing xml tag

### CODE REVIEW

**Comment by nekiro** [comment]
You are sure you understand how chances works? 30000 is 30%, 3000 is 3%, 300 is 0.3%, 30 is 0.03%

**Comment by dnvd** [comment]
I watched a few old videos for reference and this change looked better to me.
Also, if the values you present here are correct why am I getting errors in console when using values >1000?

**Comment by nekiro** [comment]
Hmm, it might be I confused loot chances to summon chances. I'll look it up later.

**Review by nekiro — APPROVED** [review]
Yep, I was wrong, max chance value for summons is 100

**Pull request merged**
